# Generated by Django 2.1.5 on 2019-02-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tests.Test'),
        ),
    ]
