# Generated by Django 2.1.5 on 2019-02-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tests', '0005_auto_20190213_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtestanswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tests.Question'),
        ),
    ]
