# Generated by Django 2.1.5 on 2019-02-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tests', '0007_auto_20190213_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='note',
        ),
    ]
