# Generated by Django 2.1.5 on 2019-02-15 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_tests', '0008_auto_20190215_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtest',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
