# Generated by Django 2.1.5 on 2019-02-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tests', '0011_auto_20190218_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=300, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='runtest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='runtestanswers',
            name='answer',
            field=models.CharField(max_length=300, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='runtestanswers',
            name='question',
            field=models.CharField(max_length=300, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
