# Generated by Django 2.1.5 on 2019-02-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tests', '0013_auto_20190226_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='app_tests.Test'),
        ),
        migrations.AlterField(
            model_name='runtestanswers',
            name='run_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_test', to='app_tests.RunTest'),
        ),
    ]
