version: '3'
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - db
    links:
      - redis

  redis:
    image: "redis:alpine"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tests_db
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=123456

  celery:
    build: .
    command: celery -A app_tests worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: gunicorn -w 2 pyFormers.wsgi:application
    volumes:
      - .:/app
    links:
      - redis

volumes:
  postgres_data:
