version: '3'
services:
  redis:
    image: "redis:alpine"

  db:
    image: postgres
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=tests_db
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=123456
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    depends_on:
      - db


